qitechgmbh/control

.github/workflows/rust.yml
=> Fix Rust Action

control-core/src/actors/stepper_driver_el70x1/mod.rs, electron/src/components/RefreshIndicator.tsx, electron/src/lib/decimal.ts, electron/src/machines/extruder/HeatingZone.tsx, electron/src/machines/extruder/extruder1/Extruder1ControlPage.tsx, electron/src/machines/winder/TensionArm.tsx, electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/act.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/tension_arm.rs
=> Zero Tension Arm

control-core/src/actors/stepper_driver_el70x1/mod.rs, control-core/src/controllers/mod.rs, control-core/src/controllers/pid.rs, control-core/src/converters/mod.rs, control-core/src/converters/step_converter.rs, control-core/src/lib.rs, control-core/src/socketio/namespace.rs, electron/src/components/Toast.tsx, electron/src/control/EditValue.tsx, electron/src/control/TimeSeriesValue.tsx, electron/src/control/units.tsx, electron/src/machines/extruder/extruder1/Extruder1ControlPage.tsx, electron/src/machines/winder/Spool.tsx, electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/Winder2Settings.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/act.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/clamp_revolution.rs, server/src/machines/winder2/linear_spool_speed_controller.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs, server/src/machines/winder2/spool_speed_controller.rs, server/src/machines/winder2/tension_arm.rs
=> Sync Tension Arm to Spool

nixos/os/configuration.nix
=> Fixes Multitouch on NixOS

control-core/src/actors/analog_function_generator.rs, control-core/src/actors/analog_input_getter.rs, control-core/src/actors/digital_input_logger.rs, control-core/src/actors/digital_output_blinker.rs, control-core/src/actors/digital_output_blinkers.rs, control-core/src/actors/digital_output_setter.rs, control-core/src/actors/mod.rs, control-core/src/actors/stepper_driver_el70x1/mod.rs, control-core/src/actors/stepper_driver_max_speed.rs, control-core/src/actors/stepper_driver_pulse_train/mod.rs, control-core/src/actors/temperature_input_logger.rs, control-core/src/controllers/pid.rs, docs/actors.md, docs/io.md, server/src/ethercat/loop.rs, server/src/machines/winder2/act.rs, server/src/machines/winder2/linear_spool_speed_controller.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/spool_speed_controller.rs, server/src/machines/winder2/tension_arm.rs
=> Use `std::time::Instant`

electron/src/components/Alert.tsx, electron/src/components/BackButton.tsx, electron/src/components/Icon.tsx, electron/src/components/Toast.tsx, electron/src/components/ToggleTheme.tsx
=> replace `size={}` with tailwindcss `size-` class

docs/threading.md, server/src/ethercat/init.rs, server/src/ethercat/loop.rs, server/src/main.rs, server/src/socketio/init.rs
=> Use `smol`

control-core/src/ethercat/interface_discovery.rs, nixos/modules/qitech.nix, nixos/os/configuration.nix, server/src/ethercat/setup.rs
=> Fix `qitech-control-servcer` service not starting

electron/src/components/FullscreenButton.tsx, electron/src/main.ts, nixos/os/home.nix
=> Fullscreen App at start in NixOS

control-core/src/actors/digital_input_logger.rs, control-core/src/ethercat/eeprom_identification.rs, ethercat-eeprom-dump/src/ls.rs, ethercat-hal/src/devices/el1008.rs, ethercat-hal/src/devices/el7031/mod.rs, ethercat-hal/src/devices/el7041_0052/mod.rs, ethercat-hal/src/devices/mod.rs, ethercat-hal/src/io/digital_input.rs, ethercat-hal/src/pdo/el70x1.rs
=> Implement `DigitalInputDevice` for `EL7031-0000` and `EL7041-0052`

Cargo.lock, control-core/src/actors/analog_input_getter.rs, ethercat-hal/Cargo.toml, ethercat-hal/src/devices/el3001.rs, ethercat-hal/src/devices/el3021.rs, ethercat-hal/src/devices/el3024.rs, ethercat-hal/src/io/analog_input/mod.rs, ethercat-hal/src/io/analog_input/physical.rs, ethercat-hal/src/io/analog_input_dummy.rs, server/src/machines/winder2/new.rs, server/src/machines/winder2/tension_arm.rs
=> Add `AnalogInputValue` to `AnalogInputState`

ethercat-hal/src/devices/el1008.rs, ethercat-hal/src/devices/el7031_0030/coe.rs, ethercat-hal/src/devices/el7031_0030/mod.rs, ethercat-hal/src/devices/el7031_0030/pdo.rs, ethercat-hal/src/devices/mod.rs, ethercat-hal/src/pdo/el70x1.rs
=> Add `EL7031_0030`

control-core/src/socketio/namespace.rs, ethercat-hal-derive/src/lib.rs, ethercat-hal/src/pdo/mod.rs, server/src/machines/winder2/api.rs, server/src/socketio/main_namespace/mod.rs
=> Fix Memory Leak

electron/src/machines/winder/Spool.tsx, electron/src/machines/winder/winder2/Winder2Settings.tsx, server/src/machines/winder2/new.rs
=> Fix Spool Speed

electron/src/control/ControlGrid.tsx, electron/src/machines/dre/DiameterVisualisation.tsx, electron/src/machines/dre/dre1/Dre1ControlPage.tsx, electron/src/machines/dre/dre1/Dre1Graph.tsx, electron/src/machines/dre/dre1/Dre1Page.tsx, electron/src/machines/dre/dre1/dre1Namespace.ts, electron/src/machines/dre/dre1/useDre.ts, electron/src/machines/types.ts, electron/src/routes/routes.tsx, server/src/machines/dre/act.rs, server/src/machines/dre/api.rs, server/src/machines/dre/mod.rs, server/src/machines/dre/new.rs, server/src/machines/winder2/new.rs
=> DRE Frontend

electron/src/machines/winder/Spool.tsx
=> Reverse `<Spool/>` animation direction

electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/Winder2Settings.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/act.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs
=> Fix #197 and #202

control-core/src/controllers/first_degree_motion/acceleration_speed_controller.rs, control-core/src/controllers/first_degree_motion/angular_acceleration_speed_controller.rs, control-core/src/controllers/first_degree_motion/linear_acceleration_speed_controller.rs, control-core/src/controllers/first_degree_motion/mod.rs, control-core/src/controllers/mod.rs, control-core/src/controllers/second_degree_motion/acceleration_position_controller.rs, control-core/src/controllers/second_degree_motion/angular_acceleration_position_controller.rs, control-core/src/controllers/second_degree_motion/angular_jerk_speed_controller.rs, control-core/src/controllers/second_degree_motion/jerk_speed_controller.rs, control-core/src/controllers/second_degree_motion/linear_acceleration_position_controller.rs, control-core/src/controllers/second_degree_motion/linear_jerk_speed_controller.rs, control-core/src/controllers/second_degree_motion/mod.rs, control-core/src/uom_extensions/angular_jerk.rs, control-core/src/uom_extensions/jerk.rs, control-core/src/uom_extensions/mod.rs, electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/main.ts, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs, server/src/machines/winder2/puller_speed_controller.rs, server/src/machines/winder2/spool_speed_controller.rs, server/src/machines/winder2/traverse_controller.rs
=> Improve acceleration of winder steppers

server/src/ethercat/setup.rs, server/src/loop.rs
=> Exit program if loop fails

README.md, electron/src/control/units.tsx, electron/src/machines/mock/mock1/Mock1ControlPage.tsx, electron/src/machines/mock/mock1/Mock1Page.tsx, electron/src/machines/mock/mock1/mock1Namespace.ts, electron/src/machines/mock/mock1/useMock.ts, electron/src/machines/types.ts, electron/src/routes/routes.tsx, ethercat-eeprom-dump/src/main.rs, server/Cargo.toml, server/src/machines/mock/act.rs, server/src/machines/mock/api.rs, server/src/machines/mock/mod.rs, server/src/machines/mock/new.rs, server/src/machines/mod.rs, server/src/machines/registry.rs, server/src/main.rs, server/src/mock/init.rs, server/src/mock/mod.rs, server/src/serial/devices/mock/mod.rs, server/src/serial/devices/mod.rs, server/src/serial/registry.rs
fix #231 
Run the server in mock mode with `--features mock-machine`. This also disables serial & ethercat machines.
=> Add Mock Machine 0x7

flake.lock, flake.nix
=> Use nixpkgs `25.05`

control-core/src/helpers/loop_trottle.rs, control-core/src/helpers/mod.rs, server/src/loop.rs, server/src/main.rs
=> Throttle Loops agains high CPU usage

electron/src/machines/extruder/extruder2/extruder2Namespace.ts
=> fixed timeseries in Extruder2

Cargo.lock, server/Cargo.toml, server/src/main.rs
=> Use `jemalloc`

electron/src/control/EditValue.tsx
=> Continuously change the value when pressing down a [-] [+] button

ethercat-hal/src/devices/el3001.rs, ethercat-hal/src/devices/el3021.rs, ethercat-hal/src/devices/el3024.rs, ethercat-hal/src/devices/el7031_0030/mod.rs, ethercat-hal/src/io/analog_input/physical.rs, ethercat-hal/src/io/analog_input_dummy.rs, server/src/machines/extruder1/screw_speed_controller.rs, server/src/machines/winder2/tension_arm.rs
=> pressure readout is now accurate and shows up in frontend

server/src/machines/extruder1/new.rs, server/src/machines/extruder1/temperature_controller.rs
=> added a hardcoded limit for extruder temperature_controllers

electron/src/machines/extruder/HeatingZone.tsx, electron/src/machines/extruder/extruder2/Extruder2Settings.tsx, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/extruder/extruder2/useExtruder.ts, server/src/machines/extruder1/act.rs, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/new.rs, server/src/machines/extruder1/screw_speed_controller.rs
=> 251 add a configurable limit for pressure

server/src/machines/winder2/traverse_controller.rs
=> In traversing mode turn around based on theshhold not point

control-core/src/ethercat/eeprom_identification.rs, docs/identification.md, ethercat-eeprom-dump/src/read.rs
fix #224
This order makes sematically more sense. SHould me berged before the first machine is shipped
=> Swap Machine and Serial Word Addresses

server/src/machines/winder2/mod.rs
=> Wrap tension arm angle from 270:360 to -90:0

electron/src/control/units.tsx, electron/src/machines/extruder/HeatingZone.tsx, electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/extruder/extruder2/useExtruder.ts, server/src/machines/extruder1/act.rs, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/new.rs, server/src/machines/extruder1/temperature_controller.rs
=> 290 add a wattage graph for heatingzone

server/src/serial/devices/dre/mod.rs
=> fix dre panic

electron/src/helpers/ipc/context-exposer.ts, electron/src/helpers/ipc/listeners-register.ts, electron/src/helpers/ipc/nixos/nixos-channels.ts, electron/src/helpers/ipc/nixos/nixos-context.ts, electron/src/helpers/ipc/nixos/nixos-listeners.ts, electron/src/helpers/nixos_helpers.ts, electron/src/setup/ChooseVersionPage.tsx, electron/src/types.d.ts
=> Show NixOS generations on "Update" page

Cargo.lock, server/Cargo.toml
=> Bump OpenTelemetry Dependencies

nixos/os/home.nix
=> Fix NixOS settings with wrong units

electron/src/control/SelectionGroup.tsx
=> Selection buttons can have a confirmation prompt

server/src/logging/mod.rs
=> Reduce logging of ethercrab

control-core/src/actors/mitsubishi_inverter_rs485/mod.rs, electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx, electron/src/machines/extruder/extruder2/Extruder2Settings.tsx, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/extruder/extruder2/useExtruder.ts, ethercat-hal/src/devices/el6021.rs, server/src/machines/extruder1/act.rs, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mod.rs
=> 360 show inverter errors and recover

electron/src/machines/laser/laser1/Laser1Graph.tsx
=> fixed assignment error

electron/src/machines/extruder/extruder2/Extruder2Page.tsx, electron/src/routes/routes.tsx
=> added extruder graphs

control-core/src/actors/mitsubishi_inverter_rs485/mod.rs, electron/src/machines/types.ts, ethercat-hal/src/devices/el6021.rs, ethercat-hal/src/io/serial_interface.rs
=> 377 inverter state machine and el6021 incorrectly handle requestresponses

control-core/src/controllers/pid.rs, electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx, electron/src/machines/extruder/extruder2/Extruder2Settings.tsx, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/extruder/extruder2/useExtruder.ts, server/src/machines/extruder1/act.rs, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/screw_speed_controller.rs, server/src/machines/extruder1/temperature_controller.rs
This just re adds the configuration part for the pressure pid, additional issue is making it prettier. fix #386
=> 386 add configuration for pressure pid

electron/src/machines/extruder/extruder2/useExtruder.ts
=> Fixed Mode button and Regulation button switching back and forth

nixos/os/configuration.nix
=> Add Wireshark

electron/package-lock.json, electron/package.json, electron/src/assets/markdown/mock/manual.md, electron/src/helpers/ipc/update/update-channels.ts, electron/src/helpers/ipc/update/update-context.ts, electron/src/helpers/ipc/update/update-listeners.ts, electron/src/helpers/update_helpers.ts, electron/src/setup/ChangelogPage.tsx, electron/src/setup/ChooseVersionPage.tsx, electron/src/setup/UpdateExecutePage.tsx, electron/src/stores/updateStore.ts, electron/src/types.d.ts
=> Make an update cancelable

Cargo.lock, control-core/Cargo.toml, control-core/src/helpers/interpolation.rs, electron/src/machines/winder/winder2/Winder2Settings.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/adaptive_spool_speed_controller.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/minmax_spool_speed_controller.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs, server/src/machines/winder2/spool_speed_controller.rs, server/src/machines/winder2/traverse_controller.rs
=> Improve spool speed controller (again)

electron/src/machines/winder/winder2/Winder2Settings.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/adaptive_spool_speed_controller.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/spool_speed_controller.rs
=> Make `AdaptiveSpoolSpeedController` Core Parameters Customizable

control-core/src/controllers/clamping_timeagnostic_pid.rs, control-core/src/controllers/mod.rs, control-core/src/controllers/pid.rs, control-core/src/controllers/timeagnostic_pid.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/screw_speed_controller.rs, server/src/machines/extruder1/temperature_controller.rs
=> 440 add clamping to all error values for timeagnosticpid

control-core/src/socketio/namespace.rs, server/src/socketio/init.rs
=> Disconnect all sockets when `Namespace` is `drop`ped

electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/Winder2Graphs.tsx, electron/src/machines/winder/winder2/Winder2Settings.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/act.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs, server/src/machines/winder2/traverse_controller.rs
=> Use only a StateEvent and LiveValuesEvent on Winder V2

electron/src/machines/extruder/extruder2/extruder2Namespace.ts, server/src/machines/extruder1/new.rs
=> 465 now emits state on extruder startup

control-core/src/controllers/clamping_timeagnostic_pid.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/screw_speed_controller.rs
=> 467 pid pressure mode overshoots drastically when switching from rpm

control-core/src/actors/mitsubishi_inverter_rs485/mod.rs
=> 475 inverter actor only waits when necessary

electron/src/machines/mock/mock1/Mock1ControlPage.tsx, electron/src/machines/mock/mock1/mock1Namespace.ts, electron/src/machines/mock/mock1/useMock.ts, server/src/machines/mock/act.rs, server/src/machines/mock/api.rs, server/src/machines/mock/mod.rs, server/src/machines/mock/new.rs
=> Use only a StateEvent and LiveValuesEvent on Laser V1

control-core/src/socketio/namespace.rs, electron/src/control/EditValue.tsx, electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx, electron/src/machines/extruder/extruder2/Extruder2Settings.tsx, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/extruder/extruder2/useExtruder.ts, electron/src/machines/laser/laser1/Laser1ControlPage.tsx, electron/src/machines/laser/laser1/laser1Namespace.ts, electron/src/machines/laser/laser1/useLaser1.ts, electron/src/machines/mock/mock1/Mock1ControlPage.tsx, electron/src/machines/mock/mock1/mock1Namespace.ts, electron/src/machines/mock/mock1/useMock.ts, electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/Winder2Settings.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/new.rs, server/src/machines/laser/api.rs, server/src/machines/laser/mod.rs, server/src/machines/laser/new.rs, server/src/machines/mock/api.rs, server/src/machines/mock/mod.rs, server/src/machines/mock/new.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs, server/src/main.rs
=> Emit default state

docs/nixos/quick-start.md
=> 138 update nixos quickstart guidemd to match current installation flow

electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/Winder2Graphs.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/act.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs
=> 471 add winder auto stop or pull after n meters of filament

electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx
=> added confirmation for extrusion mode based on temperature

electron/src/machines/laser/DiameterVisualisation.tsx
=> clamped diameter visualisation to avoid large circles

electron/src/control/EditValue.tsx, electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx
=> 501 raise pressure limit of extruder and add confirmation to EditValue

cargo_run_linux.sh
=> Set caps also for real time

electron/src/lib/preset/preset.ts, electron/src/lib/preset/presetStore.ts
=> Fix loading presets if the store does not exist yet

electron/src/control/units.tsx, electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx, electron/src/machines/extruder/extruder2/Extruder2Graph.tsx, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/extruder/extruder2/useExtruder.ts, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mitsubishi_cs80/mod.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/screw_speed_controller.rs
This PR-Introcues Voltage, Current and Power Monitoring for the Extruder Motor/Inverter.
=> 519 show inverter voltagecurrent

nixos/packages/electron.nix
=> added niceness value to wrapper

electron/src/machines/winder/winder2/Winder2ControlPage.tsx
Adds the functionality of resetting the wound distance even when the winding process is running. When running a dialog appears as a warning.
=> 550 allow wound distance reset during winding

electron/package.json
- **Fix typo in machineIdentification**
- **Allow running linter with fix option**
=> Allow running linter with fix option

control-core/src/realtime.rs, nixos/os/configuration.nix, server/src/ethercat/setup.rs, server/src/loop.rs
=> testing with cores 2,3 isolated

electron/src/client/socketioStore.ts, electron/src/components/graph/handlers.ts, electron/src/lib/constants.ts, electron/src/machines/buffer/buffer1/buffer1Namespace.ts, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, electron/src/machines/laser/laser1/laser1Namespace.ts, electron/src/machines/mock/mock1/mock1Namespace.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/buffer1/act.rs, server/src/machines/extruder1/act.rs, server/src/machines/laser/act.rs
=> 588 limit backend and frontend to 30 fps

nixos/os/configuration.nix, nixos/packages/electron.nix
=> 591 improve electron frame times

docs/developer-docs/code-style-backend.md
=> 511 add a code styling document

Cargo.lock, cargo_run_linux.sh, control-core/src/modbus/mod.rs, control-core/src/serial/mod.rs, control-core/src/serial/panic.rs, control-core/src/serial/serial_detection.rs, server/Cargo.toml, server/src/serial/devices/laser/mod.rs
- **Remove unmaintained serial crate in favor of serialport**
- **Fix permission issues for USB serial devices**
- **Allow serial connection errors to bubble up and actually log them**
Fix #356
=> Improve serial conneciton handling

Cargo.toml, control-core-derive/Cargo.toml, control-core-derive/src/lib.rs, control-core/Cargo.toml, control-core/src/helpers/hasher_serializer.rs, control-core/src/helpers/mod.rs, control-core/src/socketio/event.rs, electron/src/machines/extruder/extruder2/extruder2Namespace.ts, server/Cargo.toml, server/src/machines/extruder1/act.rs, server/src/machines/extruder1/api.rs, server/src/machines/extruder1/mod.rs, server/src/machines/extruder1/new.rs, server/src/machines/laser/act.rs, server/src/machines/laser/api.rs, server/src/machines/laser/mod.rs, server/src/machines/laser/new.rs, server/src/machines/mock/act.rs, server/src/machines/mock/api.rs, server/src/machines/mock/mod.rs, server/src/machines/mock/new.rs, server/src/machines/winder2/act.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/new.rs
=> 575 automatically send stateevent when changed

server/src/ethercat/setup.rs
=> set wait_loop_delay to zero

electron/src/machines/winder/winder2/Winder2ControlPage.tsx, electron/src/machines/winder/winder2/Winder2Graphs.tsx, electron/src/machines/winder/winder2/useWinder.ts, electron/src/machines/winder/winder2/winder2Namespace.ts, server/src/machines/winder2/adaptive_spool_speed_controller.rs, server/src/machines/winder2/api.rs, server/src/machines/winder2/mod.rs, server/src/machines/winder2/spool_speed_controller.rs
=> 722 remove estimated diameter value

electron/src/helpers/ipc/nixos/nixos-listeners.ts
=> added collect-garbage on each delete

Cargo.lock, control-core/Cargo.toml, control-core/src/lib.rs, control-core/src/machines/api.rs, control-core/src/rest/mutation.rs, control-core/src/video_streaming/mod.rs
All the added features are behind a feature flag `video-streaming`
=> Add video streaming api

server/Cargo.toml, server/src/ethercat/setup.rs, server/src/loop.rs
=> 748 add feature flag or env var for setting loop timeout

electron/package-lock.json, electron/package.json, electron/src/components/Terminal.tsx, electron/src/helpers/ipc/update/update-context.ts, electron/src/helpers/update_helpers.ts, electron/src/setup/Trobleshoot.tsx, electron/src/setup/UpdateExecutePage.tsx, electron/src/stores/logsStore.ts, electron/src/stores/updateStore.ts, nixos/modules/qitech.nix
=> 425 fix terminal component issues v2

server/src/machines/winder2/emit.rs, server/src/machines/winder2/mod.rs
=> refactored winder2's emit methods to emit.rs

nixos/modules/qitech.nix, server/src/main.rs
=> added CAP_IPC_LOCK and added memory locking

server/src/machines/aquapath1/new.rs, server/src/machines/extruder1/new.rs
=> 790 refactor aquapath newrs to match others
